# ----------------------- #
#      User Configs       #
# ----------------------- #

name: Thais Hamilton
title: Protoceratops Developer
gravatar_email: thamilto@thoughtworks.com
# don't forget to edit your "about" on _includes/about.md
# for more information about markdown, consider giving a look at some examples and basics in the follow urls:
# http://daringfireball.net/projects/markdown/basics
# http://en.wikipedia.org/wiki/Markdown



# ----------------------- #
#       Info Configs      #
# ----------------------- #

info:
  location: Porto Alegre
  code: Java, Ruby # Programmer? Put your programming languages and technologies here
  company: ThoughtWorks
  university: PUCRS
  interests: dinosaurs, photography, functional programming, dogs
  email: 


# ----------------------- #
#      Social Configs     #
# ----------------------- #

# Put your usernames here. Only usernames, without links.

social:
  facebook:
  flickr:
  foursquare:
  # Note about github: write down your_username/your_repository if you want to show a repository page, instead of your github account.
  github: thaishamilton
  goodreads:
  # Note about google+: Your googleplus username should be that huge number in your url (example: for https://plus.google.com/u/1/112176414644635750645/posts, your username is 112176414644635750645).
  # For google+ pages, you may find this huge number written down 2 times. We only need it once.
  googleplus: 
  instagram:
  lastfm: 
  linkedin:
  quora:
  stackoverflow:
  twitter: 
  rss:


# Now you should put your links.

links:
  -
    title: 
    url: 

# ----------------------- #
#      Project Configs    #
# ----------------------- #

# Google Analytics
google_analytics_tracking_id:

# Only make changes here if you _realy_ know what you're doing. Just an advice.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
